# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=None, max_length=255)),
                ('lname', models.CharField(default=None, max_length=255)),
                ('email', models.CharField(default=None, max_length=255, unique=True)),
                ('password', models.CharField(default=None, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('phone', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.IntegerField()),
                ('farm_name', models.CharField(default=None, max_length=255)),
                ('farm_avatar', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(default=None, max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('microsecond', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
