# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=None, max_length=255)),
                ('member_1', models.CharField(default=None, max_length=20)),
                ('member_2', models.CharField(default=None, max_length=20)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=None, max_length=255)),
                ('sender', models.CharField(default=None, max_length=20)),
                ('receiver', models.CharField(default=None, max_length=20)),
                ('message', models.CharField(default=None, max_length=20)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
            ],
        ),
    ]
