# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-15 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chats_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(default=None, max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('microsecond', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(default=None, max_length=255)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('day', models.IntegerField(default=0)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('microsecond', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
